# Site settings
title: Corporate Chaplaincy Consulting
description: For-profit Corporate Chaplaincy is an effective chaplaincy business model that allows you to focus on the clients of your chaplaincy organization.
keywords: For-profit corporate chaplaincy,chaplaincy business model,chaplaincy organization
baseurl: "http://www.corpchaps.com/"
permalink: /:categories/:title/
image: http://www.corpchaps.com/_img/interface/logo.png
imagefolder: https://googledrive.com/host/0B-rUPb5gojEtSTFMU3FPb19yaDA/
docfolder: https://googledrive.com/host/0B-rUPb5gojEteThPR1lHNFZremM/
publicfolder: https://googledrive.com/host/0B16RYgIOGJNPam5RZ3lHMGstZWs
url: "http://www.corpchaps.com"
include: ['_css','_js','_img']
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
#markdown: kramdown
#kramdown:
#  input: GFM
